### PR TITLE
adding tool_name param to GA event pushes

### PR DESCRIPTION
**Pull request by Guntrisoft**

### CODE REVIEW

**Comment by Guntrisoft** [comment]
@benbarnett @pmcostello

**Comment by benbarnett** [comment]
This is the one that should have 3 different tools: `mortg_calc`, `stamp_calc` & `afford_calc`

Can run through it with you I'm familiar with this codebase

**Comment by Guntrisoft** [comment]
@benbarnett have made the alterations to record the correct tool_name and have made sure that the cucumber tests continue to pass

**Comment by benbarnett** [comment]
Looks good :+1:

**Comment by asmega** [comment]
:+1:

**Comment by Tr4pSt3R** [comment]
@Guntrisoft heyyyy buddy! hahaha

**Pull request closed without merging**
