### PR TITLE
7544 - rails 4.2 compitablity changes

### PR DESCRIPTION
**Pull request by jongilbraith**
Very straight forward one, this.

### CODE REVIEW

**Comment by jriga** [comment]
👍

**Comment by jongilbraith** [comment]
Cheers @jriga.

Going to mark this WIP for the time being as there's nobody else around to actually give a second thumb.

**Comment by jongilbraith** [comment]
Forgot that @pmcostello is not out, but merely wfh, so removing WIP status!

**Comment by pmcostello** [comment]
sorry for the delay, I've pulled this branch into the local copy of frontend master and all looks good
nice work! 👍 from me

**Comment by jongilbraith** [comment]
Cheers @pmcostello

**Pull request merged**
