### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by Tr4pSt3R**

### CODE REVIEW

**Comment by neoeno** [comment]
Think this might not be what you intended?

**Comment by Tr4pSt3R** [comment]
@neoeno yeah had to split them up into separate succint PRs

https://github.com/moneyadviceservice/mortgage_calculator/pull/232
and 
https://github.com/moneyadviceservice/mortgage_calculator/pull/233

**Comment by neoeno** [comment]
I mean that the diff is just whitespace!

**Comment by Tr4pSt3R** [comment]
@neoeno it was just to get around the disabled button. I will just rip it apart and do it again

**Pull request closed without merging**
