### PR TITLE
[DEV APPROVED]Add items to second screen of stamp duty calculator

### PR DESCRIPTION
**Pull request by JiggyPete**
Follow on from PR: [Removing Page 3 and links to it](https://github.com/moneyadviceservice/mortgage_calculator/pull/266)

This PR adds the following items to the second page of the stamp duty calculator, which used to be in the, now removed, third page.

- "Did you know"
- "Find out more"
- "Mortgage Calculator" button
- "Affordability" button
- "Stamp Duty to pay..." results section underneath the slider.

**Before**
screen shot 2016-11-30 at 10 47 29

**After**
screen shot 2016-11-30 at 10 47 41

### CODE REVIEW

**Comment by slaywell** [comment]
Couple of visual things:

1. Could we align the Heading with the copy below?
image

2. The line-height on the callout box on mobile is a bit tight:
image

**Comment by slaywell** [comment]
Otherwise looks good. I've recently (today) done some visual work on the Callouts that change the appearance, when this is rebased against latest master this might change slightly.

**Comment by JiggyPete** [comment]
@slaywell the styling of the desktop will be coming in the next PR, tablet PR after that, mobile PR after that, then non-JS PR as per the request on Monday.

**Comment by slaywell** [comment]
In that case... 👍

**Comment by rnalexander** [comment]
:+1: :shipit:

**Pull request merged**
