### PR TITLE
update translation en file for mortgage calculator

### PR DESCRIPTION
**Pull request by akenzua**
[TP12274](https://maps.tpondemand.com/RestUI/Board.aspx#page=board/5175634625349962976&appConfig=eyJhY2lkIjoiOUM2MjFGQzAzOEIzQTVDNDU1NjRCMUIxQ0FENkZBOTYifQ==&boardPopup=userstory/12274/silent)

This PR did some copy changes on the MH Mortgage calculator.

### CODE REVIEW

**Comment by masbuild** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is huge. Consider next time to split up the workinto multiple PRs. A good guide about small PRs can be seenhere(link to mas-standards - small PRs guide)</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">It looks like this is a Rails engine, but no changes to <a href="https://github.com/moneyadviceservice/mortgage_calculator/blob/85ad7939947315b13b19c37abc8fed49f93e8171/lib/mortgage_calculator/version.rb">lib/mortgage_calculator/version.rb</a> detected. Did you forget to bump the version?</td>
    </tr>
  </tbody>
</table>

At Money Advice Service, we use Danger gem, to ensure that our commits and pull requests follow [standards](https://github.com/moneyadviceservice/mas-standards/blob/master/Dangerfile). If you think one of the points here has been raised in error (or shouldn't be in our standards), open an issue or pull request on [our Danger config](https://github.com/moneyadviceservice/mas-standards).

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by davidtrussler** [comment]
Can we remove the files in the format `spec/dummy/screenshot_*` from this PR? We don't need to commit those.

**Comment by davidtrussler** [comment]
The `en` changes look fine. I'll review again once the `cy` changes are made.

**Comment by akenzua** [comment]
> Can we remove the files in the format `spec/dummy/screenshot_*` from this PR? We don't need to commit those.

I will look at that, though I did not touch it.

**Review by davidtrussler — APPROVED** [review]
OK, this looks good to me now that the Welsh is complete. 👍 
If you can remove the test files (`spec/dummy/screenshot_*`) that would be better for a cleaner commit history but not absolutely necessary I guess.

**Review by davidtrussler — APPROVED** [review]
The additional changes look good to me. 👍 

Could you try to delete the test files from the PR before committing?

**Pull request merged**
