### PR TITLE
[fix] welsh text copy issue

### PR DESCRIPTION
**Pull request by Tr4pSt3R**

### CODE REVIEW

**Comment by benlovell** [comment]
These should be separate commits.

**Comment by Tr4pSt3R** [comment]
@benlovell another lookie :+1: 
 
And this: https://github.com/moneyadviceservice/mortgage_calculator/pull/233

**Comment by benlovell** [comment]
You still didn't manage to split them up. My advice is that you close this PR, go back and try again from scratch. Also, remember to `bundle` when you bump the version.

**Comment by Tr4pSt3R** [comment]
Cheers @benlovell will do that

**Comment by benlovell** [comment]
Np. Give me a shout if you need any help sir :wave:

**Pull request closed without merging**
