### PR TITLE
Update versions of karma-jasmine and phantomjs

### PR DESCRIPTION
**Pull request by tomas-stefano**
This fixes the
https://go.test.moneyadviceservice.org.uk/go/tab/build/detail/mortgage_calculator/627/test/1/test

### CODE REVIEW

**Comment by rnalexander** [comment]
:+1:

**Comment by asmega** [comment]
:+1:

**Comment by Tr4pSt3R** [comment]
:+1: excellent work! Tomas

**Comment by tomas-stefano** [comment]
Thanks all :)

**Pull request merged**
