### PR TITLE
[DEV APPROVED] Sdc number rounding changes

### PR DESCRIPTION
**Pull request by willhall88**
Feature branch for SDC rounding:
Built out of below approved PRs - 
#314 
#315 
#316 
#317

### CODE REVIEW

**Comment by willhall88** [comment]
♻️  rebased

**Comment by rnalexander** [comment]
Looks good!  👍

**Comment by tomas-stefano** [comment]
👍 👍

**Comment by johnplayer1982** [comment]
Pulled, test ran and manually tested :+1:

**Pull request merged**
