### PR TITLE
11352 y/e updates lbtt calculator

### PR DESCRIPTION
**Pull request by davidtrussler**
[TP11352](https://maps.tpondemand.com/entity/11352-ye-land-and-buildings-transaction-tax)

This work makes a number of changes to the Land and Buildings Transaction Tax Calculator to reflect Year End tax changes (see individual commits):
- Change 1: updates copy
- Change 2: updates copy and associated cucumber definitions and steps
- Change 3: updates copy
- Change 4: updates calculations and associated cucumber expectations
- Change 5: updates copy and associated cucumber expectations
- Change 6: updates copy and associated cucumber definitions

### CODE REVIEW

**Comment by masbuild** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>app/helpers/mortgage_calculator/land_and_buildings_transaction_taxes_helper.rb</td>
      <td>13</td>
      <td>Lint/UnusedMethodArgument: Unused method argument - <code>rate</code>. If it’s necessary, use <code>_</code> or <code>_rate</code> as an argument name to indicate that it won’t be used. You can also write as <code>second_home_rate(*)</code> if you want the method to accept any arguments but don’t care about them.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">It looks like this is a Rails engine, but no changes to <a href="https://github.com/moneyadviceservice/mortgage_calculator/blob/859d0573afa5383ed33d154c66b5c65905af032c/lib/mortgage_calculator/version.rb">lib/mortgage_calculator/version.rb</a> detected. Did you forget to bump the version?</td>
    </tr>
  </tbody>
</table>

At Money Advice Service, we use Danger gem, to ensure that our commits and pull requests follow [standards](https://github.com/moneyadviceservice/mas-standards/blob/master/Dangerfile). If you think one of the points here has been raised in error (or shouldn't be in our standards), open an issue or pull request on [our Danger config](https://github.com/moneyadviceservice/mas-standards).

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ladamsatmaps19** [comment]
Looks OK to me but I'm not sure about the check status above?

**Comment by davidtrussler** [comment]
> Looks OK to me but I'm not sure about the check status above?

Thanks @ladamsatmaps19 - I think the error that was highlighted is now fixed.

**Comment by kiggundu** [comment]
need to up the version aof the gem and merge with TP11346 before merging

**Pull request merged**
