### PR TITLE
Use h1 for mortgage calcs

### PR DESCRIPTION
**Pull request by benbarnett**

### CODE REVIEW

**Comment by Guntrisoft** [comment]
@benbarnett probably a bit picky but should this not be BEM'd?

**Comment by neoeno** [comment]
I remember us having reports back from DAC about sensible document hierarchy. Does this result in a sensible one when included in frontend?

**Comment by esbel** [comment]
:+1:

**Comment by benbarnett** [comment]
@Guntrisoft BEM'd? How come? We already style `h1`s?

@neoeno this will bring it inline with the [stamp duty calc](https://www.moneyadviceservice.org.uk/en/tools/house-buying/stamp-duty-calculator) and yeah mean a sensible document structure. There's no other `h1`s on these pages

**Comment by neoeno** [comment]
:+1:

**Comment by neoeno** [comment]
Though looking at the current one this results in a jump from h1 to h3, which DAC have objected to before. Probably needs addressing in future.

**Comment by Guntrisoft** [comment]
fair enough - just used to putting classes on everything when it comes to BEM'g stuff, and never styling default elements! :+1:

**Comment by benbarnett** [comment]
@neoeno good point, I'll update those to `h2`

@Guntrisoft yeah generally true, but we're not applying any styling to these so can get away with it here :)

**Comment by benbarnett** [comment]
@neoeno I've tried to reflow the rest, seems logical in a browser. Could you give it a quick once over?

**Comment by neoeno** [comment]
Will do.

**Comment by neoeno** [comment]
There are still a couple: 

screenshot 2015-02-11 11 28 07

screenshot 2015-02-11 11 29 33

The footer messes up the document structure anyway, so there's a limit to how good we can make it. On the other tools — mortage affordability and stamp duty — WAVE flags document hierarchy warnings in the footer.

[There's a good chrome extension for finding this stuff.](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh)

**Comment by benbarnett** [comment]
Nice one, I've fixed those up now. Thanks Caden!

**Pull request merged**
