### PR TITLE
12170 - 12011 - 12078 - Mortgage Affordability Urgent Changes

### PR DESCRIPTION
**Pull request by andreferreiradlw**
[TP12170](https://maps.tpondemand.com/entity/12170-change-legacy-grey-to-mh-grey) - Change legacy grey to MH grey
[TP12011](https://maps.tpondemand.com/entity/12011-next-steps-links-need-to-be) - Next steps links need to be updated
[TP12078](https://maps.tpondemand.com/entity/12078-mortgage-affordability-responsiveness-issues) - Responsiveness issues

This PR addresses the most urgent issues on the Mortgage Affordability tool. Fixes some responsiveness issues on multiple pages and updates copy and multiple links.

### CODE REVIEW

**Comment by masbuild** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          3 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">There are code changes, but no corresponding tests. Please include tests if this PR introduces any modifications in behavior. If this is a refactor PR, please ignore the message.Refer to our mas standards guides about opening a PR<a href="link-to-the-mas-standards-about-opening-a-pr">here</a></td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is huge. Consider next time to split up the workinto multiple PRs. A good guide about small PRs can be seenhere(link to mas-standards - small PRs guide)</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">It looks like this is a Rails engine, but no changes to <a href="https://github.com/moneyadviceservice/mortgage_calculator/blob/ce1f02ed10e3960717597df1f608bc6ea0ff9033/lib/mortgage_calculator/version.rb">lib/mortgage_calculator/version.rb</a> detected. Did you forget to bump the version?</td>
    </tr>
  </tbody>
</table>

At Money Advice Service, we use Danger gem, to ensure that our commits and pull requests follow [standards](https://github.com/moneyadviceservice/mas-standards/blob/master/Dangerfile). If you think one of the points here has been raised in error (or shouldn't be in our standards), open an issue or pull request on [our Danger config](https://github.com/moneyadviceservice/mas-standards).

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by davidtrussler — APPROVED** [review]
LGTM! 👍

**Comment by davidtrussler** [comment]
I have approved this PR but one thing I noticed (that is not directly a comment on these changes) is that links to Welsh language pages are now in English which seems poor practice from the point of view of SEO and for Welsh language users generally. I will add this comment to the TP card as well as I think it's something worth looking at more generally.

**Comment by andreferreiradlw** [comment]
> I have approved this PR but one thing I noticed (that is not directly a comment on these changes) is that links to Welsh language pages are now in English which seems poor practice from the point of view of SEO and for Welsh language users generally. I will add this comment to the TP card as well as I think it's something worth looking at more generally.

@davidtrussler Thanks for approving! Yeah, I also found that weird and from what I've seen on the rest of the cards, I think it's going to be like that for everything now and I'm not sure why either. I think it's worth pointing that out to Venetia

**Pull request merged**
